export const LOAD_COLLATOR ='LOAD_COLLATOR';
export const MOOMBEAM_LOADING ='MOOMBEAM_LOADING';
export const MOOMBEAM_FAIL ='MOOMBEAM_FAIL';

//moon rever
export const LOAD_MOONREVER ='LOAD_MOONREVER';
export const MOONREVER_LOADING ='MOONREVER_LOADING';
export const MOONREVER_FAIL ='MOONREVER_FAIL';

// Delegator
export const LOAD_SEARCH = 'SEARCH';
export const LOAD_SEARCH_MOONRIVER = 'LOAD_SEARCH_MOONRIVER';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_FAILED = 'SEARCH_FAILED';